metadata
cookbook 'logrotate'
cookbook 'yum'
cookbook 'java'
cookbook 'build-essential'
cookbook 'runit'
cookbook 'apache2'
cookbook 'yumrepo', git: 'git://github.com/bryanwb/cookbook-yumrepo.git'
cookbook 'rbenv'
cookbook 'ruby_build'
cookbook 'minitest-handler', git: 'git://github.com/btm/minitest-handler-cookbook.git'
cookbook 'elasticsearch', git: 'git://github.com/elasticsearch/cookbook-elasticsearch.git'
